[package]
name = "roc_error_macros"
description = "Provides macros for consistent reporting of errors in Roc's rust code."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
