[package]
name = "roc_collections"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Domain-specific collections created for the needs of the compiler."

[dependencies]
fnv.workspace = true
im.workspace = true
im-rc.workspace = true
wyhash.workspace = true
bumpalo.workspace = true
hashbrown.workspace = true
bitvec.workspace = true
