[package]
name = "roc_code_markup"
description = "Our own markup language for Roc code. Used by the editor and the docs."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_ast = { path = "../ast" }
roc_module = { path = "../compiler/module" }
roc_error_utils = { path = "../utils/error" }

palette.workspace = true

bumpalo.workspace = true
serde.workspace = true
snafu.workspace = true
