[package]
name = "roc_wasm_module"
version = "0.0.1"
edition = "2021"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
description = "Parse, manipulate, and serialize WebAssembly modules."

[dependencies]
roc_error_macros = { path = "../error_macros" }

bitvec.workspace = true
bumpalo.workspace = true
