[package]
name = "roc_test_utils"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Utility functions used all over the code base."

[dependencies]
pretty_assertions = "1.3.0"
remove_dir_all = "0.8.0"

[dev-dependencies]
