[package]
name = "roc_test_utils"
description = "Utility functions used all over the code base."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
pretty_assertions.workspace = true
remove_dir_all.workspace = true

[dev-dependencies]
