config:
  commands-show-output: false
  fenced-code-language: false
  first-line-heading: false
  line-length: false
  no-duplicate-heading: false
  no-emphasis-as-heading: false
  no-inline-html: false
  no-trailing-punctuation: false

ignores:
  - "crates/vendor/**/*.md"

# Enable fixing of linting errors reported by rules that emit fix information 
fix: true

# Disable the support of HTML comments within Markdown content
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true
