config:
  blanks-around-headings: false
  blanks-around-lists: false
  commands-show-output: false
  emphasis-style: false
  fenced-code-language: false
  first-line-heading: false
  list-indent: false
  line-length: false
  list-marker-space: false
  single-title: false
  single-trailing-newline: false
  no-bare-urls: false
  no-duplicate-heading: false
  no-emphasis-as-heading: false
  no-hard-tabs: false
  no-inline-html: false
  no-multiple-blanks: false
  no-space-in-code: false
  no-trailing-punctuation: false
  no-trailing-spaces: false
  ul-indent: false
  ul-style: false

ignores:
  - "crates/vendor/**/*.md"

# Enable fixing of linting errors reported by rules that emit fix information 
fix: true

# Disable the support of HTML comments within Markdown content
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true
