[package]
name = "roc"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]

[dependencies]
dogged = { version = "0.2.0", optional = true }
log = "0.4.8"
petgraph = { version = "0.4.5", optional = true }
im-rc = "13.0.0"
fraction = "0.6.2"
num = "0.2.0"
fxhash = "0.2.1"
bumpalo = "2.6.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm8-0" }

[dev-dependencies]
pretty_assertions = "0.5.1"
maplit = "1.0.1"
indoc = "0.3.3"
quickcheck = "0.8"
quickcheck_macros = "0.8"
