[workspace]

members = [
    "compiler",
    "compiler/region",
    "compiler/collections",
    "compiler/module",
    "compiler/parse",
    "compiler/can",
    "compiler/problem",
    "compiler/types",
    "compiler/uniqueness",
    "compiler/builtins",
    "compiler/constrain",
    "vendor/ena",
    "vendor/pathfinding"
]
