[package]
name = "roc"
version = "0.1.0"
authors = ["Richard Feldman <richard.t.feldman@gmail.com>"]

[dependencies]
dogged = { version = "0.2.0", optional = true }
log = "0.4"
petgraph = { version = "0.4.5", optional = true }
combine = "3.8.1"
im-rc = "13.0.0"
smallvec = "0.6.9"

[dev-dependencies]
pretty_assertions = "0.5.1"
maplit = "1.0.1"
