[workspace]

members = [
    "compiler",
    "compiler/region",
    "compiler/collections",
    "compiler/module",
    "compiler/parse",
    "compiler/can",
    "compiler/types",
    "vendor/ena",
    "vendor/pathfinding"
]
