name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM
      run: ./ci/install-llvm.sh 8
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
