[package]
name = "roc_types"
description = "Various representations and utilities for dealing with types in the Roc compiler."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
roc_error_macros = {path="../../error_macros"}
roc_debug_flags = {path="../debug_flags"}
roc_serialize = {path="../serialize"}

ven_pretty = { path = "../../vendor/pretty" }

bumpalo.workspace = true
static_assertions.workspace = true
