[package]
name = "roc_wasm_interp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roc_wasm_module = { path = "../wasm_module" }

bitvec.workspace = true
bumpalo.workspace = true
