[package]
name = "roc_wasm_interp"
description = "A WebAssembly interpreter for testing the compiler."

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "roc_wasm_interp"
path = "src/main.rs"

[dependencies]
roc_wasm_module = { path = "../wasm_module" }

rand.workspace = true
bitvec.workspace = true
bumpalo.workspace = true
clap.workspace = true
