[package]
name = "roc_wasm_interp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A WebAssembly interpreter for testing the compiler."

[[bin]]
name = "roc_wasm_interp"
path = "src/main.rs"

[dependencies]
roc_wasm_module = { path = "../wasm_module" }
rand = "0.8.4"
bitvec.workspace = true
bumpalo.workspace = true
clap.workspace = true
