[package]
name = "roc_parse"
description = "Implements the Roc parser, which transforms a textual representation of a Roc program to an AST."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
"parse_debug_trace" = []

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }

bumpalo.workspace = true
encode_unicode.workspace = true

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
pretty_assertions.workspace = true
indoc.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true

[[bench]]
name = "bench_parse"
harness = false
