[package]
name = "roc_packaging"
description = "Functionality for packaging Roc source code - e.g. for distribution over the network"

version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
roc_parse = { path = "../compiler/parse" }
roc_error_macros = { path = "../error_macros" }

tar.workspace = true # used for `roc build --tar`
brotli.workspace = true # used for decompressing tarballs over HTTPS, if the server supports brotli
flate2.workspace = true
blake3.workspace = true
base64-url.workspace = true
bumpalo.workspace = true
fs_extra.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest.workspace = true

[dev-dependencies]
tempfile.workspace = true