[package]
name = "roc_highlight"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"
description = "For syntax highlighting, starts with a string and returns our markup nodes."

[dependencies]
roc_code_markup = { path = "../code_markup"}

peg.workspace = true
