[package]
name = "roc_highlight"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "For syntax highlighting, starts with a string and returns our markup nodes."

[dependencies]
roc_code_markup = { path = "../code_markup"}

peg.workspace = true
