[package]
name = "roc_highlight"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"
description = "For syntax highlighting Roc code such as the generated documentation."

[dependencies]
roc_region = { path = "../compiler/region" }
roc_parse = { path = "../compiler/parse" }
html-escape = "0.2"
