[package]
name = "roc_serialize"
description = "Provides helpers for serializing and deserializing to/from bytes."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
