[package]
name = "roc_load"
version = "0.1.0"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2018"

[dependencies]
roc_load_internal = { path = "../load_internal" }

[build-dependencies]
roc_load_internal = { path = "../load_internal" }
