[package]
name = "test_wasm_util"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# roc_module = { path = "../module" }
# roc_mono = { path = "../mono" }

wasmer = { version = "2.0.0", default-features = false, features = ["default-cranelift", "default-universal"] }

roc_std = { path = "../../roc_std" }
