[package]
name = "test_wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# roc_module = { path = "../module" }
# roc_mono = { path = "../mono" }

wasmer = { version = "2.0.0", default-features = false, features = ["default-llvm", "default-universal"] }
wasmer-wasi = "2.0.0"

roc_collections = { path = "../collections" }
roc_std = { path = "../../roc_std" }
bumpalo = { version = "3.8.0", features = ["collections"] }
roc_gen_wasm = { path = "../gen_wasm" }
roc_can = { path = "../can" }
roc_builtins = { path = "../builtins" }
roc_load = { path = "../load" }
roc_types = { path = "../types" }
roc_module = { path = "../module" }
indoc = "1.0.3"
libc = "0.2.106"
target-lexicon = "0.12.2"
