[package]
name = "roc_module"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]
edition = "2018"

[dependencies]
roc_region = { path = "../region" }
roc_collections = { path = "../collections" }
bumpalo = "2.6"
inlinable_string = "0.1.0"
lazy_static = "1.4"

[dev-dependencies]
pretty_assertions = "0.5.1 "
maplit = "1.0.1"
indoc = "0.3.3"
