[package]
name = "roc_repl_expect"
description = "Supports evaluating expect and printing contextual information when they fail."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_build = { path = "../compiler/build" }
roc_builtins = { path = "../compiler/builtins" }
roc_can = { path = "../compiler/can" }
roc_collections = { path = "../compiler/collections" }
roc_error_macros = { path = "../error_macros" }
roc_gen_llvm = { path = "../compiler/gen_llvm" }
roc_load = { path = "../compiler/load" }
roc_module = { path = "../compiler/module" }
roc_mono = { path = "../compiler/mono" }
roc_packaging = { path = "../packaging" }
roc_parse = { path = "../compiler/parse" }
roc_region = { path = "../compiler/region" }
roc_repl_eval = { path = "../repl_eval" }
roc_reporting = { path = "../reporting" }
roc_std = { path = "../roc_std" }
roc_target = { path = "../compiler/roc_target" }
roc_types = { path = "../compiler/types" }

bumpalo.workspace = true
inkwell.workspace = true
libc.workspace = true
libloading.workspace = true
target-lexicon.workspace = true

[dev-dependencies]
roc_build = { path = "../compiler/build", features = ["target-aarch64", "target-x86_64"] }

indoc.workspace = true
pretty_assertions.workspace = true
strip-ansi-escapes.workspace = true
tempfile.workspace = true


[lib]
name = "roc_repl_expect"
path = "src/lib.rs"
