[package]
name = "roc_unify"
description = "Implements Roc's unification algorithm, the heartstone of Roc's type inference."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[dependencies.roc_collections]
path = "../collections"

[dependencies.roc_error_macros]
path = "../../error_macros"

[dependencies.roc_module]
path = "../module"

[dependencies.roc_types]
path = "../types"

[dependencies.roc_debug_flags]
path = "../debug_flags"

[dependencies.roc_tracing]
path = "../../tracing"

[dependencies.roc_checkmate]
path = "../checkmate"

[dependencies.roc_solve_schema]
path = "../solve_schema"
