[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "roc_unify"
version.workspace = true
description = "Implements Roc's unification algorithm, the heartstone of Roc's type inference."

[dependencies]
bitflags = "1.3.2"

[dependencies.roc_collections]
path = "../collections"

[dependencies.roc_error_macros]
path = "../../error_macros"

[dependencies.roc_module]
path = "../module"

[dependencies.roc_types]
path = "../types"

[dependencies.roc_debug_flags]
path = "../debug_flags"

[dependencies.roc_tracing]
path = "../../tracing"
