[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "roc_alias_analysis"
version.workspace = true

[dependencies]
morphic_lib = {path = "../../vendor/morphic_lib"}
roc_collections = {path = "../collections"}
roc_error_macros = {path = "../../error_macros"}
roc_module = {path = "../module"}
roc_mono = {path = "../mono"}
roc_debug_flags = {path = "../debug_flags"}
bumpalo.workspace = true
