[package]
name = "roc_alias_analysis"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
morphic_lib = { path = "../../vendor/morphic_lib" }
roc_collections = { path = "../collections" }
roc_debug_flags = { path = "../debug_flags" }
roc_error_macros = { path = "../../error_macros" }
roc_module = { path = "../module" }
roc_mono = { path = "../mono" }

bumpalo.workspace = true
