[package]
name = "valgrind"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dev-dependencies]
cli_utils = { path = "../cli_utils" }
roc_build = { path = "../compiler/build" }
roc_linker = { path = "../linker" }
roc_load = { path = "../compiler/load" }
roc_mono = { path = "../compiler/mono" }
roc_packaging = { path = "../packaging" }
roc_reporting = { path = "../reporting" }

bumpalo.workspace = true
indoc.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true

[package.metadata.cargo-udeps.ignore]
development = ["roc_build", "roc_linker"]