[package]
name = "valgrind"
version = "0.1.0"
edition = "2021"
authors = ["The Roc Contributors"]
license = "UPL-1.0"

[dev-dependencies]
roc_cli = { path = "../cli" }
cli_utils = { path = "../cli_utils" }
roc_build = { path = "../compiler/build" }
roc_mono = { path = "../compiler/mono" }
roc_load = { path = "../compiler/load" }
roc_reporting = { path = "../reporting" }
roc_linker = { path = "../linker" }
roc_packaging = { path = "../packaging" }
bumpalo.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true
indoc.workspace = true
