[package]
name = "valgrind"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dev-dependencies]
cli_utils = { path = "../cli_utils" }
roc_build = { path = "../compiler/build" }
roc_mono = { path = "../compiler/mono" }
roc_load = { path = "../compiler/load" }
roc_reporting = { path = "../reporting" }
roc_linker = { path = "../linker" }
roc_packaging = { path = "../packaging" }

bumpalo.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true
indoc.workspace = true
