[package]
name = "soa"
description = "Struct-of-Array helpers"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
pretty_assertions.workspace = true

[dev-dependencies]
