[package]
name = "roc_linker"
description = "A surgical linker for Roc"

version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
name = "roc_linker"
path = "src/lib.rs"

[dependencies]
roc_mono = { path = "../compiler/mono" }
roc_collections = { path = "../compiler/collections" }
roc_error_macros = { path = "../error_macros" }
roc_load = { path = "../compiler/load" }
roc_target = { path = "../compiler/roc_target" }
roc_packaging = { path = "../packaging" }
roc_reporting = { path = "../reporting" }

bumpalo.workspace = true
iced-x86.workspace = true
memmap2.workspace = true
object.workspace = true
mach_object.workspace = true
serde.workspace = true
bincode.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true


[dev-dependencies]
indoc.workspace = true
libc.workspace = true
