[package]
name = "roc_debug_flags"
description = "Environment variables that can be toggled to aid debugging of the compiler itself."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
