[package]
name = "test_derive"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Tests Roc's auto-derivers."

[[test]]
name = "test_derive"
path = "src/tests.rs"

[dev-dependencies]
roc_collections = { path = "../collections" }
roc_module = { path = "../module" }
roc_builtins = { path = "../builtins" }
roc_load_internal = { path = "../load_internal" }
roc_can = { path = "../can" }
roc_derive_key = { path = "../derive_key" }
roc_derive = { path = "../derive", features = ["debug-derived-symbols", "open-extension-vars"] }
roc_target = { path = "../roc_target" }
roc_types = { path = "../types" }
roc_packaging = { path = "../../packaging" }
roc_reporting = { path = "../../reporting" }
roc_constrain = { path = "../constrain" }
roc_region = { path = "../region" }
roc_solve = { path = "../solve" }
roc_debug_flags = { path = "../debug_flags" }

ven_pretty = { path = "../../vendor/pretty" }

bumpalo.workspace = true
insta.workspace = true
