[package]
authors.workspace = true
description = "Rust wrapper for a WebAssembly test platform built on libc"
edition.workspace = true
license.workspace = true
name = "wasi_libc_sys"
repository.workspace = true
version.workspace = true

[build-dependencies]
roc_utils = {path = "../utils"}