[package]
authors = ["The Roc Contributors"]
description = "Rust wrapper for a WebAssembly test platform built on libc"
edition = "2021"
license = "UPL-1.0"
name = "wasi_libc_sys"
repository = "https://github.com/roc-lang/roc"
version = "0.0.1"

[build-dependencies]
roc_utils = {path = "../utils"}