[package]
name = "fs"
description = "no_std filesystem access. These operations all use native OS strings and do not allocate."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[target.'cfg(windows)'.dependencies]
widestring = { version = "1.1.0", default-features = false }
