[package]
name = "roc_utils"
description = "Utility functions used all over the code base."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
snafu.workspace = true

[dev-dependencies]
