[package]
name = "roc_utils"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Utility functions used all over the code base."

[dependencies]
snafu = { version = "0.7.1", features = ["backtraces"] }

[dev-dependencies]
