[package]
name = "roc_command_utils"
description = "Utility functions used all over the code base to call eternal apps like zig."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[dev-dependencies]
