[package]
name = "roc_solve_problem"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Provides types to describe problems that can occur during solving."

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
roc_types = { path = "../types" }
roc_can = { path = "../can" }
roc_problem = { path = "../problem" }
roc_exhaustive = { path = "../exhaustive" }
