[package]
name = "roc_fmt"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"
description = "The roc code formatter."

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
roc_parse = { path = "../parse" }
roc_test_utils = { path = "../../test_utils" }
bumpalo.workspace = true 

[dev-dependencies]
pretty_assertions.workspace = true
indoc.workspace = true
walkdir.workspace = true
