[package]
name = "roc_fmt"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "The roc code formatter."

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
roc_parse = { path = "../parse" }
bumpalo.workspace = true 
