[package]
authors = ["The Roc Contributors"]
edition = "2018"
license = "UPL-1.0"
name = "roc_unify"
version = "0.1.0"

[dependencies]
bitflags = "1.3.2"

[dependencies.roc_collections]
path = "../collections"

[dependencies.roc_module]
path = "../module"

[dependencies.roc_types]
path = "../types"
