[package]
name = "roc_docs"
description = "Generates html documentation from Roc files and is used for Rocs builtins."

version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
roc_ast = { path = "../ast" }
roc_load = { path = "../compiler/load" }
roc_builtins = { path = "../compiler/builtins" }
roc_can = { path = "../compiler/can" }
roc_code_markup = { path = "../code_markup"}
roc_module = { path = "../compiler/module" }
roc_region = { path = "../compiler/region" }
roc_types = { path = "../compiler/types" }
roc_parse = { path = "../compiler/parse" }
roc_target = { path = "../compiler/roc_target" }
roc_collections = { path = "../compiler/collections" }
roc_highlight = { path = "../highlight"}
roc_packaging = { path = "../packaging"}
roc_reporting = { path = "../reporting"}

pulldown-cmark.workspace = true
bumpalo.workspace = true
snafu.workspace  = true
peg.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
