[package]
name = "roc_glue"
description = "Generates code needed for platform hosts to communicate with Roc apps. This tool is not necessary for writing a platform in another language, however, it's a great convenience! Currently supports Rust platforms, and the plan is to support any language via a plugin model."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
roc_std = { path = "../roc_std"}
roc_can = { path = "../compiler/can" }
roc_mono = { path = "../compiler/mono" }
roc_load = { path = "../compiler/load" }
roc_reporting = { path = "../reporting" }
roc_packaging = { path = "../packaging" }
roc_types = { path = "../compiler/types" }
roc_builtins = { path = "../compiler/builtins" }
roc_module = { path = "../compiler/module" }
roc_collections = { path = "../compiler/collections" }
roc_target = { path = "../compiler/roc_target" }
roc_error_macros = { path = "../error_macros" }
roc_tracing = { path = "../tracing" }

bumpalo.workspace = true
fnv.workspace = true
indexmap.workspace = true
strum.workspace = true
strum_macros.workspace = true
target-lexicon.workspace = true

[dev-dependencies]
cli_utils = { path = "../cli_utils" }
dircpy.workspace = true

indoc.workspace = true
pretty_assertions.workspace = true
tempfile.workspace = true
