[package]
name = "test_mono_macros"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Macros for use in test_mono."

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.81", features = ["full", "extra-traits"] }
quote = "1.0.10"
proc-macro2 = "1.0.32"
