[package]
name = "roc_region"
description = "Data structures for storing source-code-location information, used heavily for contextual error messages."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
static_assertions.workspace = true
