[package]
name = "roc_region"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Data structures for storing source-code-location information, used heavily for contextual error messages."

[dependencies]
static_assertions.workspace = true
