[package]
name = "host"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
roc_std = { path = "../../../roc_std" }
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }

[workspace]
