[package]
name = "roc_target"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"
description = "Provides types and helpers for compiler targets such as default_x86_64."

[dependencies]

strum.workspace = true
strum_macros.workspace = true
target-lexicon.workspace = true
