[package]
name = "roc_work"
description = "This is used in loading."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../collections" }
roc_module = { path = "../module" }
roc_error_macros = { path = "../../error_macros" }
