[package]
name = "cli_test_utils"
description = "Provides shared code for cli tests, cli benchmarks, glue tests, valgrind crate."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
roc_collections = { path = "../compiler/collections" }
roc_load = { path = "../compiler/load" }
roc_module = { path = "../compiler/module" }
roc_reporting = { path = "../reporting" }
roc_command_utils = { path = "../utils/command" }
roc_cli = { path = "../cli" }

bumpalo.workspace = true
criterion.workspace = true
regex.workspace = true
serde.workspace = true
tempfile.workspace = true
lazy_static.workspace = true
const_format.workspace = true

[target.'cfg(unix)'.dependencies]
rlimit.workspace = true
