[package]
name = "roc_std"
version = "0.1.0"
authors = ["Richard Feldman <oss@rtfeldman.com>"]
repository = "https://github.com/rtfeldman/roc"
readme = "README.md"
edition = "2018"
description = "Rust representations of Roc data structures"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
