[package]
name = "valgrind"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dev-dependencies]
cli_test_utils = { path = "../cli_test_utils" }
roc_command_utils = { path = "../utils/command" }
roc_build = { path = "../compiler/build" }
roc_linker = { path = "../linker" }
roc_load = { path = "../compiler/load" }
roc_mono = { path = "../compiler/mono" }
roc_packaging = { path = "../packaging" }
roc_reporting = { path = "../reporting" }

bumpalo.workspace = true
indoc.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true

[features]
default = ["target-aarch64", "target-x86_64", "target-wasm32"]

target-aarch64 = ["roc_build/target-aarch64"]
target-arm = []
target-wasm32 = []
target-x86 = []
target-x86_64 = ["roc_build/target-x86_64"]

[package.metadata.cargo-udeps.ignore]
development = ["roc_build", "roc_linker"]
