[package]
name = "roc_ident"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Implements data structures used for efficiently representing small strings, like identifiers."
