[package]
name = "roc_std"
description = "Rust representations of Roc data structures"
readme = "README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
arrayvec.workspace = true
serde = { workspace = true, optional = true }
static_assertions.workspace = true

[dev-dependencies]
indoc.workspace = true
libc.workspace = true
pretty_assertions.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true
serde_json.workspace = true

[features]
serde = ["dep:serde"]
std = []
