[package]
authors.workspace = true
description = "Rust representations of Roc data structures"
edition.workspace = true
license.workspace = true
name = "roc_std"
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
static_assertions = "1.1.0"
arrayvec = "0.7.2"
serde = { version = "1", optional = true }

[dev-dependencies]
indoc = "1.0.3"
libc = "0.2.135"
pretty_assertions = "1.0.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde_json = "1.0.83"

[features]
std = []
serde = ["dep:serde"]
