[package]
name = "roc_module"
version = "0.0.1"
authors = ["The Roc Contributors"]
edition = "2021"
license = "UPL-1.0"
description = "Implements data structures used for efficiently representing unique modules and identifiers in Roc programs."

[dependencies]
roc_region = { path = "../region" }
roc_ident = { path = "../ident" }
roc_collections = { path = "../collections" }
roc_error_macros = {path = "../../error_macros"}
bumpalo = { version = "3.11.0", features = ["collections"] }
static_assertions = "1.1.0"
snafu = { version = "0.7.1", features = ["backtraces"] }

[features]
default = []
debug-symbols = []
