[package]
name = "nightly_benches"
authors = ["The Roc Contributors"]
edition = "2021"
license = "UPL-1.0"
version = "0.0.1"

[dependencies]

[dev-dependencies]
cli_utils = { path = "../cli/cli_utils" }

criterion-perf-events.workspace = true
criterion.workspace = true
perfcnt.workspace = true

[[bench]]
name = "events_bench"
harness = false
