[package]
name = "nightly_benches"
version = "0.0.1"
edition = "2021"
authors = ["The Roc Contributors"]
license = "UPL-1.0"

[dependencies]

[dev-dependencies]
cli_utils = { path = "../cli/cli_utils" }

criterion.workspace = true
criterion-perf-events.workspace = true
perfcnt.workspace = true

[[bench]]
name = "events_bench"
harness = false
