[package]
name = "roc_problem"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Provides types to describe problems that can occur when compiling Roc code."

[dependencies]
roc_collections = { path = "../collections" }
roc_region = { path = "../region" }
roc_module = { path = "../module" }
roc_types = { path = "../types" }
roc_parse = { path = "../parse" }
