[package]
name = "test_compile"
description = "Utility functions for starting from strings of code and compiling various IRs."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_builtins = { path = "../compiler/builtins" }
roc_derive = { path = "../compiler/derive", features = [
    "debug-derived-symbols",
] }
roc_region = { path = "../compiler/region" }
roc_collections = { path = "../compiler/collections" }
roc_load = { path = "../compiler/load" }
roc_parse = { path = "../compiler/parse" }
roc_can = { path = "../compiler/can" }
roc_module = { path = "../compiler/module" }
roc_types = { path = "../compiler/types" }
roc_problem = { path = "../compiler/problem" }
roc_constrain = { path = "../compiler/constrain" }
roc_reporting = { path = "../reporting" }
roc_target = { path = "../compiler/roc_target" }
roc_solve = { path = "../compiler/solve" }
roc_solve_problem = { path = "../compiler/solve_problem" }

roc_specialize_types.workspace = true
bumpalo.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
