[package]
name = "roc_tracing"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Utilities for setting up tracing at various executable entry points."

[dependencies]
tracing = { version = "0.1.36", features = ["release_max_level_off"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-appender = "0.2.2"
