[package]
name = "roc_tracing"
description = "Utilities for setting up tracing at various executable entry points."

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
