[package]
name = "roc_late_solve"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Provides type unification and solving primitives from the perspective of the compiler backend."

[dependencies]
roc_types = { path = "../types" }
roc_can = { path = "../can" }
roc_derive = { path = "../derive" }
roc_module = { path = "../module" }
roc_unify = { path = "../unify" }
roc_solve = { path = "../solve" }
roc_collections = { path = "../collections" }
roc_error_macros = { path = "../../error_macros" }

bumpalo.workspace = true 
