on: [pull_request]

name: Benchmarks

jobs:
  benchmark:
    name: benchmark
    runs-on: self-hosted
    container: vulpix/ubuntu-20-04-benchmarks
    timeout-minutes: 60
    steps:
      - name: print PATH
        run: echo $PATH

      - uses: actions/checkout@v2

      - name: Expose needed modules
        run: cd editor && ./prep_benchmarks.sh && cd ..

      - name: cargo bench
        run: cargo bench