on: [pull_request]

name: Benchmarks

env:
  RUST_BACKTRACE: 1

jobs:
  prep-dependency-container:
    name: cd cli; cargo criterion
    runs-on: [self-hosted, i7-6700K]
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "trunk" # benchmarking on trunk first in order to compare results
          clean: "false" # we want to keep the benchmark folder

      - name: Earthly version
        run: earthly --version

      - name: on trunk; install dependencies, build, cd cli, benchmark with criterion
        run: ./ci/safe-earthly.sh +bench-roc

      - uses: actions/checkout@v2
        with:
          clean: "true"

      - name: on current branch; install dependencies, build, cd cli, benchmark with criterion
        run: ./ci/safe-earthly.sh +bench-roc
