on: [pull_request]

name: Benchmarks

jobs:
  benchmark:
    name: benchmark
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Log CPU model
        run: cat /proc/cpuinfo  | grep name | uniq

      - name: Expose needed modules
        run: cd editor && ./prep_benchmarks.sh && cd ..

      - name: cargo bench
        with:
          command: bench