on: [pull_request]

name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  prep-dependency-container:
    name: install + test inside earthly
    runs-on: self-hosted
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2

      - name: Earthly version
        run: earthly --version

      - name: build container roc-deps-tests:latest
        run: earthly +all
