on: [pull_request]

name: CI

env:
  RUSTC_WRAPPER: ./ci/sccache

jobs:
  test:
    name: fmt, clippy, test, test --release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Install CI Libraries
        run: sudo ./ci/install-ci-libraries.sh 10

      - name: Run Zig tests
        run: pushd compiler/builtins/bitcode; ./run-tests.sh; popd;

      - name: Enable LLD
        run: sudo ./ci/enable-lld.sh

      - uses: actions-rs/toolchain@v1
        name: Install Rust Toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        name: rustfmt version
        with:
          command: fmt
          args: --version

      - uses: actions-rs/cargo@v1
        name: cargo fmt --check
        with:
          command: fmt
          args: --all -- --check

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        name: clippy version
        with:
          command: clippy
          args: -V

      - uses: actions-rs/cargo@v1
        name: cargo clippy
        with:
          command: clippy
          args: -- -D warnings

      - uses: actions-rs/cargo@v1
        name: cargo test -- --ignored
        continue-on-error: true
        with:
          command: test
          args: -- --ignored

      - uses: actions-rs/cargo@v1
        name: cargo test --release
        with:
          command: test
          args: --release

      - run: ./ci/sccache --show-stats
