on: [pull_request]

name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  prep-dependency-container:
    name: fmt, clippy, test --release
    runs-on: self-hosted
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2

      - name: Earthly version
        run: earthly --version

      - name: Make empty cache folders if they do not exist
        run: mkdir -p oldcache; mkdir -p oldindex; mkdir -p oldbin; mkdir -p oldgitdb;

      - name: install dependencies, build, run zig tests, rustfmt, clippy, cargo test --release 
        run: earthly +test-all
