on:
  schedule:
    - cron:  '0 9 * * 1' # 9=9am utc+0, 1=monday

name: Nightly Release macOS x86_64

env:
  ZIG_VERSION: 0.9.1
  LLVM_SYS_130_PREFIX: /usr/local/opt/llvm

jobs:
  test-and-build:
    name: Rust tests, build and package nightly release
    runs-on: [macos-12]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        run: |
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-macos-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz
          echo "${GITHUB_WORKSPACE}/zig-macos-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
      - name: zig version
        run: zig version
      - name: Install LLVM
        run: brew install llvm@13
      # build has to be done before tests #2572
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
      - name: execute rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked # no --release yet until #3166 is fixed
      - name: write version to file
        run: ./ci/write_version.sh
      - name: package release
        run: ./ci/package_release.sh roc_darwin_x86_64.tar.gz
      - name: Create pre-release with test_archive.tar.gz
        uses: Anton-4/deploy-nightly@1609d8dfe211b078674801113ab7a2ec2938b2a9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/roc-lang/roc/releases/51880579/assets{?name,label}
          release_id: 51880579
          asset_path: ./roc_darwin_x86_64.tar.gz
          asset_name: roc_nightly-macos_x86_64-$$.tar.gz # $$ inserts 6 char commit hash and date (YYYY-MM-DD)
          asset_content_type: application/gzip
          max_releases: 3

