on:  
  schedule:
    - cron:  '0 0 * * *'

name: Nightly Release Build

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install LLVM
        run: sudo ./ci/install-llvm.sh 8
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: update cargo (needed for Inkwell)
        with:
          command: update
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test --release

  juild:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        name: update cargo (needed for Inkwell)
        with:
          command: update
      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build --release

  # clippy:
  #   name: Clippy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install LLVM
  #       run: sudo ./ci/install-llvm.sh 8
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #     - run: rustup component add clippy
  #     - uses: actions-rs/cargo@v1
  #       name: update cargo (needed for Inkwell)
  #       with:
  #         command: update
  #     - uses: actions-rs/cargo@v1
  #       name: cargo clippy
  #       with:
  #         command: clippy
  #         args: --release -- -D warnings
