on: [pull_request]

name: Nightly Release Apple Silicon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    name: Rust tests, build and package nightly release
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
      - name: zig version
        run: zig version
      - name: llvm version
        run: llc --version | grep LLVM
      - name: run tests 
        run: cargo test --locked # no --release yet until #3166 is fixed
      - name: write version to file
        run: ./ci/write_version.sh
      - name: build nightly release
        run: cargo build --locked --release
      - name: package release
        run: ./ci/package_release.sh roc_darwin_apple_silicon.tar.gz
      - name: Create pre-release with test_archive.tar.gz
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/rtfeldman/roc/releases/51880579/assets{?name,label}
          release_id: 51880579
          asset_path: ./roc_darwin_apple_silicon.tar.gz
          asset_name: roc_nightly-darwin_apple_silicon-$$.tar.gz # $$ inserts date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/gzip
          max_releases: 6

