on:
  schedule:
    - cron:  '0 9 * * *'

name: Nightly Release macOS Apple Silicon

jobs:
  test-and-build:
    name: Rust tests, build and package nightly release
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      - name: zig version
        run: zig version
      - name: llvm version
        run: llc --version | grep LLVM

      - name: run tests
        run: cargo test --locked --release
        
      - name: get commit SHA
        run:  echo "SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
        
      - name: get date
        run: echo "DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
        
      - name: build file name
        env:
            DATE: ${{ env.DATE }}
            SHA: ${{ env.SHA }}
        run: echo "RELEASE_TAR_FILENAME=roc_nightly-macos_apple_silicon-$DATE-$SHA.tar.gz" >> $GITHUB_ENV  

      - name: write version to file
        run: ./ci/write_version.sh

      - name: build nightly release
        run: cargo build --locked --release

      - name: package release
        run: ./ci/package_release.sh ${{ env.RELEASE_TAR_FILENAME }}

      - name: print short commit SHA
        run: git rev-parse --short "$GITHUB_SHA"
      - name: print date
        run: date
      - name: Upload artifact Actually uploading to github releases has to be done manually
        uses: actions/upload-artifact@v3
        with:
           name: ${{ env.RELEASE_TAR_FILENAME }}
           path: ${{ env.RELEASE_TAR_FILENAME }}
           retention-days: 4
