on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

name: Nightly Release Old Linux x86_64 using Earthly
    
jobs:
  build:
    name: build and package nightly release
    runs-on: [self-hosted, i7-6700K]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: get commit SHA
        run:  echo "SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
        
      - name: get date
        run: echo "DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
        
      - name: build file name
        env:
            DATE: ${{ env.DATE }}
            SHA: ${{ env.SHA }}
        run: echo "RELEASE_FOLDER_NAME=roc_nightly-old_linux_x86_64-$DATE-$SHA" >> $GITHUB_ENV
       
      - run: earthly --version

      - name: build release with Earthly
        env:
            RELEASE_FOLDER_NAME: ${{ env.RELEASE_FOLDER_NAME }}
        run: earthly +build-nightly-release  --RELEASE_FOLDER_NAME='$RELEASE_FOLDER_NAME'

      - name: Upload roc nightly tar. Actually uploading to github releases has to be done manually.
        uses: actions/upload-artifact@v3
        with:
           name: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
           path: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
           retention-days: 4
