on: [pull_request]

name: Nix apple silicon cargo test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  nix-apple-silicon:
    name: nix-apple-silicon
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - name: execute tests with --release
        run: nix develop -c cargo test --locked --release
