on:
  pull_request:
  
name: Nix linux arm64 cli_run tests

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    RUST_BACKTRACE: 1

jobs:
    nix-linux-arm64:
        name: nix-linux-arm64
        runs-on: [self-hosted, Linux, ARM64]
        timeout-minutes: 120
        steps:
            - uses: actions/checkout@v3
            
            # error: bootstrap-tools.tar.xz.drv': No such file or directory    
            #- name: test building default.nix
            #  run: nix-build 

            - name: execute cli_run tests with --release
              run: nix develop -c cargo test --locked --release -p roc_cli
