on:
  workflow_dispatch:

name: Test latest nightly release for macOS, ubu 20.04, ubu 22.04 x86_64

env:
  ZIG_VERSION: 0.9.1

jobs:
  test-nightly:
    name: test nightly macos 11, macos 12, ubu 20.04, ubu 22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3

      - name: fetch releases data and save to file
        run: |
          curl --request GET \
          --url https://api.github.com/repos/roc-lang/roc/releases \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --output roc_releases.json

      - name: get the url of today`s release for linux (x86_64)
        if: startsWith(matrix.os, 'ubuntu')
        run: echo "RELEASE_URL=$(./ci/get_today_release_url.sh linux_x86_64)" >> $GITHUB_ENV

      - name: get the url of today`s release for macos (x86_64)
        if: startsWith(matrix.os, 'macos')
        run: echo "RELEASE_URL=$(./ci/get_today_release_url.sh macos_x86_64)" >> $GITHUB_ENV

      - name: get the archive from the url
        run: curl -OL ${{ env.RELEASE_URL }}

      - name: remove everything in this dir except the tar # we want to test like a user who would have downloaded the release, so we clean up all files from the repo checkout
        run: ls | grep -v "roc_nightly.*tar\.gz" | xargs rm -rf

      - name: decompress the tar
        run: ls | grep "roc_nightly.*tar\.gz" | xargs tar -xzvf

      - name: delete tar
        run: ls | grep "roc_nightly.*tar\.gz" | xargs rm -rf

      - name: rename nightly folder
        run: mv roc_nightly* roc_nightly

      - name: test roc hello world
        run: cd roc_nightly && ./roc examples/helloWorld.roc

      - name: test platform switching rust
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesRust.roc

      - name: get OS to use for zig download
        if: startsWith(matrix.os, 'ubuntu')
        run: echo "OS_TYPE=linux" >> $GITHUB_ENV

      - name: get OS to use for zig download
        if: startsWith(matrix.os, 'macos')
        run: echo "OS_TYPE=macos" >> $GITHUB_ENV

      - name: Install zig
        run: |
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-${{env.OS_TYPE}}-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz
          echo "${GITHUB_WORKSPACE}/zig-${{env.OS_TYPE}}-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
      - name: zig version
        run: zig version

      - name: test platform switching zig
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesZig.roc

      - name: test platform switching c
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesC.roc



