on:
  workflow_dispatch:
# pull_request:

name: Test latest nightly releases for macOS and Linux

jobs:
  test-nightly:
    name: test nightly macos 13 (x64), macos 14 (aarch64), ubuntu 20.04-24.04 (x64), ubuntu 22.04-24.04 (aarch64)
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Delete everything except ci folder to test the release like a real user would
        run: find . -maxdepth 1 ! -name ci ! -name '.' -exec rm -rf {} +

      - name: install z3 on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install z3

      - run: zig version

      - name: Run basic tests
        run: ./ci/basic_release_test.sh ${{ matrix.os }}

      - name: Run basic tests with old release
        if: startsWith(matrix.os, 'ubuntu')
        run: ./ci/basic_release_test.sh ${{ matrix.os }} old