on:
  workflow_dispatch:

name: Test latest nightly release for macOS Apple Silicon

jobs:
  test-nightly:
    name: test nightly macos aarch64
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      
      - name: fetch releases data and save to file
        run: curl https://api.github.com/repos/roc-lang/roc/releases > roc_releases.json

      - name: get the url of today`s release for macos apple silicon
        run: echo "RELEASE_URL=$(./ci/get_today_release_url.sh silicon)" >> $GITHUB_ENV

      - name: Get the archive from the url.
        run: curl -OL ${{ env.RELEASE_URL }}

      - name: remove everything in this dir except the tar # we want to test like a user who would have downloaded the release, so we clean up all files from the repo checkout
        run: ls | grep -v "roc_nightly.*tar\.gz" | xargs rm -rf

      - name: decompress the tar
        run: ls | grep "roc_nightly.*tar\.gz" | xargs tar -xzvf

      - name: delete tar
        run: ls | grep "roc_nightly.*tar\.gz" | xargs rm -rf

      - name: rename nightly folder
        run: mv roc_nightly* roc_nightly

      - name: test roc hello world
        run: cd roc_nightly && ./roc examples/helloWorld.roc

      - name: test platform switching rust
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesRust.roc

      - name: test platform switching zig
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesZig.roc

      - name: test platform switching c
        run: cd roc_nightly && ./roc examples/platform-switching/rocLovesC.roc


        
