on: [pull_request]
#  schedule:
#    - cron:  '0 15 * * *'

name: Test latest nightly release for macOS Apple Silicon

jobs:
  test-and-build:
    name: test nightly macos aarch64
    runs-on: [self-hosted, macOS, ARM64]
    timeout-minutes: 90
    steps:
      name: fetch releases data and save to file
      run: curl https://api.github.com/repos/roc-lang/roc/releases > roc_releases.json

      name: get the url of today's release for macos apple silicon
      run: echo "RELEASE_URL=$(./ci/get_latest_release.sh)" >> $GITHUB_ENV

      name: get the archive from the url
      run: curl -OL ${{ env.RELEASE_URL }}

      name: decompress the tar
      run: ls | grep tar | xargs tar -xzvf

      name: test roc hello world
      run: ./roc examples/hello-world/main.roc


        
