[package]
name = "roc_checkmate"
description = "A framework for debugging the solver."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
roc_module = { path = "../module" }
roc_types = { path = "../types" }

serde.workspace = true
serde_json.workspace = true
